AWSTemplateFormatVersion: '2010-09-09'
Description: Deployment bucket for SAM artifacts

Parameters:
  BucketName:
    Type: String
    Default: formbridge-deployment
    Description: Base name for the deployment bucket

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          - Id: CleanupMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
        
Outputs:
  BucketName:
    Value: !Ref DeploymentBucket
    Description: Name of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
      
  BucketArn:
    Value: !GetAtt DeploymentBucket.Arn
    Description: ARN of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
      
  BucketDomainName:
    Value: !GetAtt DeploymentBucket.DomainName
    Description: Domain name of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"