AWSTemplateFormatVersion: '2010-09-09'
Description: Deployment bucket for SAM artifacts

Parameters:
  BucketName:
    Type: String
    Default: formbridge-deployment
    Description: Base name for the deployment bucket

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          - Id: CleanupMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      NotificationConfiguration:
        CloudWatchConfigurations:
          - Event: s3:ObjectCreated:*
            CloudWatchConfiguration:
              LogGroupName: !Ref DeploymentBucketLogGroup
              
  DeploymentBucketLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/s3/${BucketName}-${AWS::AccountId}'
      RetentionInDays: 14

  DeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${DeploymentBucket}/*'
              - !GetAtt DeploymentBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: AllowGitHubActionsAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/GitHubActionsDeploymentRole'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - !Sub '${DeploymentBucket}/*'
              - !GetAtt DeploymentBucket.Arn
        
Outputs:
  BucketName:
    Value: !Ref DeploymentBucket
    Description: Name of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
      
  BucketArn:
    Value: !GetAtt DeploymentBucket.Arn
    Description: ARN of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
      
  BucketDomainName:
    Value: !GetAtt DeploymentBucket.DomainName
    Description: Domain name of the deployment bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"